### ISSUE TITLE
CallStack error without explanation

### ISSUE THREAD

**Issue by smooge** [juhp/rpmbuild-order#2]
I am trying to use rpmbuild-order on Fedora 33 and found the following error with both the one shipped with Fedora 35. If you get the spec files for `binutils gcc glibc zlib texinfo gettext dejagnu flex sharutils hostname procps-ng zstd doxygen elfutil` and run commands like: 
```
$ rpmbuild-order chain binutils gcc glibc zlib texinfo gettext dejagnu flex sharutils hostname procps-ng zstd doxygen elfutils
warning: line 330: It's not recommended to have unversioned Obsoletes: Obsoletes: libmudflap
warning: line 331: It's not recommended to have unversioned Obsoletes: Obsoletes: libmudflap-devel
warning: line 332: It's not recommended to have unversioned Obsoletes: Obsoletes: libmudflap-static
warning: line 337: It's not recommended to have unversioned Obsoletes: Obsoletes: libcilkrts
warning: line 338: It's not recommended to have unversioned Obsoletes: Obsoletes: libcilkrts-static
warning: line 339: It's not recommended to have unversioned Obsoletes: Obsoletes: libmpx
warning: line 340: It's not recommended to have unversioned Obsoletes: Obsoletes: libmpx-static

rpmbuild-order: Cycles in dependencies:
binutils gcc glibc texinfo elfutils gettext flex zstd doxygen
Subcycles: 
gcc binutils
glibc gcc
texinfo glibc
gettext elfutils
elfutils gcc texinfo
doxygen gcc zstd
binutils gcc doxygen
flex doxygen gcc gettext
zstd gcc gettext flex


CallStack (from HasCallStack):
  error, called at src/Distribution/RPM/Build/Graph.hs:250:9 in rpmbuild-order-0.4.3.1-1mLKj9sZv1Dfq2mYrmZNs:Distribution.RPM.Build.Graph

```
Using different sets of packages all give the CallStack error. I am not sure how to debug what is causing this. I have tried getting more info via -v or -l and it did not seem to add anything to the report that would help debug this. I figured I should open this up as an issue at the moment.

**Comment by juhp** [comment]
Ah thanks for the report.

So actually turns out this is more a UX issue then an actual bug.
But I agree showing the stacktrace after the error message is not useful nor the right thing to do here.
So I am making a new release to fix that, since it is confusing.

Basically the human error message is above: `Cycles in dependencies: ...`
ie since there are dependency cycles among your packages it is not possible to give a build order.
I think I will reword that too to be clearer.

Also a few more general comments:
- You may be able to reduce some subcycles using boot bcond in the spec files: ie passing eg `-r--with=bootstrap` to rpmbuild-order
- Unfortunately I realised the subcycles generated are not all correct so I am going to disable that feature at least temporarily
- Noting here that fbrnch too has support for sorting _and_ building chains of packages (leveraging the library from this package)

**Comment by smooge** [comment]
Ah thanks. I was wondering about that. I was actually trying to use this tool to find the loops since well I need to know where to throw the bootstrap in when I start a large re-build cycle. I figure I am going to have all kinds of loops showing up as I am going through the entire OS.

**Comment by juhp** [comment]
Yeah, I tried on paper for the cycle that rpmbuild-order finds for your example - it is a pretty tightly connected, hehe.
But I want to add a graph output command so that one can see it easily (that won't be useful for the whole OS, but at least should make it clear for small package subsets, like the one you gave.

**Comment by juhp** [comment]
I just built [rpmbuild-order-0.4.4](https://hackage.haskell.org/package/rpmbuild-order-0.4.4/changelog) for Fedora Rawhide.
I will backport it later to current Fedora releases.

**Comment by juhp** [comment]
Here is graphviz showing the output of
`rpmbuild-order render binutils elfutils flex gettext gcc doxygen glibc texinfo zstd procps-ng`:
![Screenshot of rendered graph](https://user-images.githubusercontent.com/82731/118582100-5eb08880-b7c5-11eb-8e09-a92d9e00dd56.png).

Also the correct list of shortest path subcycles:

```
$ rpmbuild-order sort binutils elfutils flex gettext gcc doxygen glibc texinfo zstd procps-ng
:
rpmbuild-order: ordering not possible due to build dependency cycle:

binutils elfutils flex gettext gcc doxygen glibc texinfo zstd procps-ng

Shortest path subcycles: 
gcc binutils
gcc elfutils
doxygen gcc
glibc gcc
zstd gcc
glibc gcc binutils
binutils gcc elfutils
elfutils gcc gettext
doxygen gcc gettext
texinfo binutils gcc
procps-ng elfutils gcc
glibc gcc texinfo
elfutils gcc zstd
elfutils gcc gettext flex
doxygen gcc gettext flex
procps-ng elfutils gcc gettext
gettext elfutils gcc glibc
gettext elfutils gcc texinfo
```

**Comment by smooge** [comment]
Oh I like the render part. that makes it useful to try and figure out how to break some of the loops. or maybe where some of them might be superfluous. I am not sure how to feed that info back into a build order yet but thanks.

**Comment by juhp** [comment]
BTW I just noticed that the arrows are going in the opposite direction to what I expected/wanted:
ie the arrows above are going to dependents not dependencies: I plan to change that in the next release.

**Comment by juhp** [comment]
fbrnch-0.9 released today also has a graph command now.
